### ISSUE TITLE
How is this lib going to be installed?

### ISSUE THREAD

**Issue by 0x7466** [robertmuth/PyZwaver#1]
I would really like to try this lib. How do I install it?

**Comment by robertmuth** [comment]
Sorry for the superlate response.
I just got to work on this again.
I do not have pip integration yet but all you need is in the pyzwaver/ directory.

**Comment by KM4YRI** [comment]
@robertmuth Would you accept a pull request that adds a [setup.py](https://docs.python.org/3/install/index.html) to the project?  That (and maybe a few other misc files) would be enough to get it installed into the python site_packages or into a virtual environment.

I'd be willing to write it but wanted to ask in case you had any reasons to not accept a pull request for it.

**Comment by robertmuth** [comment]
@KM4YRI -  that would be great!

**Comment by KM4YRI** [comment]
@robertmuth Done: https://github.com/robertmuth/PyZwaver/pull/7
